-- tonight.lua

local c = {
    fg = '#c2c2c2',
    fg_shade_1 = '#999999',
    fg_shade_2 = '#666666',
    fg_shade_3 = '#444444',
    fg_shade_4 = '#333333',
    fg_shade_5 = '#222222',

    bg = '#202020',

    red = '#d75f5f',
    orange = '#d7875f',
    yellow = '#d8ad84',
    green = '#a8a658',
    dark_green = '#2f4f0f',
    teal = '#87afaf',
    dark_teal = '#204f4f',
    purple = '#af87af',
}

local highlights = {
    Normal   = {fg = c.fg, bg = c.bg},
    NormalNC = {link = 'Normal'},

    Comment = {fg = c.fg_shade_2},

    LineNr       = {fg = c.fg_shade_3},
    LineNrAbove  = {link = 'LineNr'},
    LineNrBelow  = {link = 'LineNr'},
    CursorLineNr = {link = 'LineNr'},
    EndOfBuffer  = {link = 'LineNr'},

    SignColumn     = {},
    ColorColumn    = {bg = c.fg_shade_5},
    CursorLine     = {link = 'ColorColumn'},
    CursorLineFold = {link = 'FoldColumn'},
    CursorLineSign = {link = 'SignColumn'},
    CursorColumn   = {link = 'CursorLine'},

    Visual    = {bg = c.fg_shade_4},
    VisualNOS = {bg = c.fg_shade_4},

    Cursor       = {fg = c.bg, bg = c.fg},
    lCursor      = {link = 'Cursor'},
    CursorIM     = {link = 'Cursor'},
    TermCursor   = {fg = c.bg, bg = c.fg_shade_2},
    TermCursorNC = {fg = c.fg_shade_2},

    CurSearch  = {fg = c.bg, bg = c.orange},
    IncSearch  = {link = 'CurSearch'},
    Search     = {fg = c.bg, bg = c.yellow},
    Substitute = {fg = c.bg, bg = c.yellow},

    StatusLine   = {fg = c.yellow, bg = c.fg_shade_4},
    StatusLineNC = {fg = c.fg_shade_1, bg = c.fg_shade_4},

    ModeMsg    = {fg = c.teal},
    MoreMsg    = {link = 'ModeMsg'},
    ErrorMsg   = {fg = c.red},
    WarningMsg = {fg = c.yellow},

    Pmenu         = {fg = c.fg, bg = c.fg_shade_4},
    PmenuSel      = {fg = c.bg, bg = c.teal},
    PmenuKind     = {link = 'Pmenu'},
    PmenuKindSel  = {link = 'PmenuSel'},
    PmenuExtra    = {link = 'Pmenu'},
    PmenuExtraSel = {link = 'PmenuSel'},
    PmenuSbar     = {bg = c.fg_shade_2},
    PmenuThumb    = {bg = c.fg_shade_1},
    QuickFixLine  = {link = 'PmenuSel'},

    WildMenu = {fg = c.bg, bg = c.teal},

    Title      = {fg = c.yellow},
    FloatTitle = {link = 'Title'},

    Conceal   = {fg = c.teal},
    Question  = {fg = c.teal},
    Directory = {fg = c.teal},

    DiffAdd    = {fg = c.fg, bg = c.dark_green},
    DiffChange = {fg = c.fg, bg = c.fg_shade_3},
    DiffDelete = {fg = c.red, bg = c.bg},
    DiffText   = {fg = c.fg, bg = c.dark_teal},

    Folded     = {bg = c.fg_shade_4},
    FoldColumn = {link = 'Folded'},

    VertSplit    = {fg = c.fg_shade_4},
    Winseparator = {link = 'VertSplit'},

    Whitespace = {fg = c.fg_shade_2},
    NonText    = {fg = c.fg_shade_2},
    MatchParen = {fg = c.fg, bg = c.fg_shade_2},

    MsgArea      = {fg = c.fg},
    MsgSeparator = {fg = c.yellow, bg = c.fg_shade_4},

    NormalFloat = {fg = c.fg, bg = c.fg_shade_4},
    FloatBorder = {fg = c.fg_shade_1},

    SpellBad   = {fg = c.red, underline = true},
    SpellCap   = {fg = c.fg, underline = true},
    SpellLocal = {link = 'Normal'},
    SpellRare  = {link = 'Normal'},

    TabLine     = {fg = c.fg, bg = c.fg_shade_4},
    TabLineFill = {bg = c.fg_shade_4},
    TabLineSel  = {fg = c.yellow, bg = c.fg_shade_4},

    WinBar   = {fg = c.fg},
    WinBarNC = {fg = c.fg, bg = c.fg_shade_4},

    Constant  = {fg = c.orange},
    String    = {fg = c.green},
    Character = {link = 'String'},
    Boolean   = {link = 'Constant'},
    Number    = {link = 'Constant'},
    Float     = {link = 'Constant'},

    Identifier = {fg = c.fg},
    Function   = {fg = c.teal},

    Statement   = {fg = c.purple},
    Conditional = {link = 'Statement'},
    Repeat      = {link = 'Statement'},
    Label       = {link = 'Statement'},
    Operator    = {link = 'Statement'},
    Keyword     = {link = 'Statement'},
    Exception   = {link = 'Statement'},

    PreProc   = {link = 'Statement'},
    Include   = {link = 'Statement'},
    Define    = {link = 'Statement'},
    Macro     = {link = 'Statement'},
    PreCondit = {link = 'Statement'},

    Type         = {fg = c.yellow},
    StorageClass = {link = 'Type'},
    Structure    = {link = 'Type'},
    Typedef      = {link = 'Type'},

    Special        = {fg = c.fg},
    SpecialKey     = {link = 'Special'},
    SpecialChar    = {link = 'Special'},
    SpecialComment = {fg = c.fg_shade_1},
    Tag            = {link = 'Special'},
    Delimiter      = {link = 'Special'},
    Debug          = {link = 'Special'},

    Underlined = {underline = true},
    Ignore     = {fg = c.bg},
    Error      = {fg = c.red},
    Todo       = {fg = c.orange},

    LspReferenceText            = {link = 'Normal'},
    LspReferenceRead            = {link = 'LspReferenceText'},
    LspReferenceWrite           = {link = 'LspReferenceText'},
    LspSignatureActiveParameter = {fg = c.bg, bg = c.teal},
    LspCodeLens                 = {link = 'LspInlayHint'},
    LspCodeLensSeparator        = {link = 'LspCodeLens'},
    LspInlayHint                = {fg = c.fg_shade_2},

    DiagnosticError          = {fg = c.red},
    DiagnosticWarn           = {fg = c.yellow},
    DiagnosticInfo           = {fg = c.teal},
    DiagnosticHint           = {fg = c.fg},
    DiagnosticOk             = {fg = c.green},
    DiagnosticUnderlineError = {fg = c.red, underline = true},
    DiagnosticUnderlineWarn  = {fg = c.yellow, underline = true},
    DiagnosticUnderlineInfo  = {fg = c.teal, underline = true},
    DiagnosticUnderlineHint  = {fg = c.fg, underline = true},
    DiagnosticUnderlineOk    = {fg = c.green, underline = true},
    DiagnosticFloatingError  = {link = 'DiagnosticError'},
    DiagnosticFloatingWarn   = {link = 'DiagnosticWarn'},
    DiagnosticFloatingInfo   = {link = 'DiagnosticInfo'},
    DiagnosticFloatingHint   = {link = 'DiagnosticHint'},
    DiagnosticFloatingOk     = {link = 'DiagnosticOk'},

    ['@boolean']                        = {link = 'Boolean'},
    ['@character']                      = {link = 'Character'},
    ['@character.special']              = {link = 'SpecialChar'},
    ['@comment']                        = {link = 'Comment'},
    ['@conditional']                    = {link = 'Conditional'},
    ['@constant']                       = {link = 'Constant'},
    ['@constant.builtin']               = {link = 'Define'},
    ['@constant.macro']                 = {link = 'Macro'},
    ['@constructor']                    = {link = 'Special'},
    ['@debug']                          = {link = 'Debug'},
    ['@define']                         = {link = 'Define'},
    ['@exception']                      = {link = 'Exception'},
    ['@field']                          = {link = 'Identifier'},
    ['@float']                          = {link = 'Float'},
    ['@function']                       = {link = 'Function'},
    ['@function.builtin']               = {link = 'Function'},
    ['@function.macro']                 = {link = 'Macro'},
    ['@include']                        = {link = 'Include'},
    ['@keyword']                        = {link = 'Keyword'},
    ['@label']                          = {link = 'Label'},
    ['@lsp.type.member']                = {link = 'Function'},
    ['@macro']                          = {link = 'Macro'},
    ['@method']                         = {link = 'Function'},
    ['@namespace']                      = {link = 'Identifier'},
    ['@number']                         = {link = 'Number'},
    ['@operator']                       = {link = 'Operator'},
    ['@parameter']                      = {link = 'Identifier'},
    ['@preproc']                        = {link = 'PreProc'},
    ['@property']                       = {link = 'Identifier'},
    ['@punctuation']                    = {link = 'Delimiter'},
    ['@repeat']                         = {link = 'Repeat'},
    ['@storageclass']                   = {link = 'StorageClass'},
    ['@string']                         = {link = 'String'},
    ['@string.escape']                  = {link = 'SpecialChar'},
    ['@string.special']                 = {link = 'SpecialChar'},
    ['@structure']                      = {link = 'Structure'},
    ['@tag']                            = {link = 'Tag'},
    ['@tag.html']                       = {link = 'Statement'},
    ['@tag.attribute.html']             = {link = 'Type'},
    ['@tag.attribute.tsx']              = {link = 'Type'},
    ['@tag.builtin.tsx']                = {link = 'Statement'},
    ['@tag.delimiter.html']             = {link = 'Function'},
    ['@tag.delimiter.tsx']              = {link = 'Function'},
    ['@text.emphasis.markdown_inline']  = {link = 'SpecialComment'},
    ['@text.literal']                   = {link = 'SpecialComment'},
    ['@text.literal.block.markdown']    = {link = 'SpecialComment'},
    ['@text.literal.markdown_inline']   = {link = 'SpecialComment'},
    ['@text.reference']                 = {link = 'Identifier'},
    ['@text.reference.markdown_inline'] = {link = 'Statement'},
    ['@text.title']                     = {link = 'Title'},
    ['@text.todo']                      = {link = 'Todo'},
    ['@text.underline']                 = {link = 'Underlined'},
    ['@text.uri']                       = {link = 'Underlined'},
    ['@type']                           = {link = 'Type'},
    ['@type.definition']                = {link = 'Typedef'},
    ['@variable']                       = {link = 'Identifier'},
}

vim.cmd('highlight clear')
vim.cmd('set t_Co=256')
vim.cmd([[let g:colors_name='tonight']])

for group, attrs in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, attrs)
end
